# Generated by Django 3.1.7 on 2021-03-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Name',
            field=models.CharField(db_column='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(db_column='img', upload_to='pictures'),
        ),
    ]
